version: "3.9"

services:

  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: speech_text_python
    restart: "no"
    working_dir: /django_application
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/django_application:cached
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    #    command: python manage.py runserver 0.0.0.0:8000
    #    command: tail -f /dev/null
    env_file:
      - .env
    #    links:
    #      - postgres
    #      - node
    #    depends_on:
    #      - postgres
    networks:
      - speech_text_dev_network

  postgres:
    image: postgres:latest
    container_name: speech_text_postgresql
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - speech_text_dev_postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    #    environment:
    #      POSTGRES_USER: user
    #      POSTGRES_PASSWORD: password
    #      POSTGRES_DB: speech_text
    networks:
      - speech_text_dev_network

  node:
    build: ./docker/node
    container_name: speech_text_node
    working_dir: /django_application
    restart: "no"
    ports:
      - "6006:6006"
    volumes:
      - ./assets:/django_application:cached
    command: tail -f /dev/null
    # command: "npm i && npm run build-dev"

volumes:
  speech_text_dev_postgres-db:

networks:
  speech_text_dev_network:
