version: "3.9"

services:

#  nginx:
#    image: nginx:latest
#    container_name: speech_text_nginx_prod
#    restart: "no"
#    working_dir: /django_application
#    ports:
#      - "80:80"
#    volumes:
#      - ./assets/static:/django_application:cached
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
#    depends_on:
#      - python
#    networks:
#      - speech_text_prod_network

  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: speech_text_python_prod
    restart: "no"
    working_dir: /django_application
    ports:
      - "8000:8000"
    volumes:
      - .:/django_application
    command: gunicorn --workers=1 --bind 0.0.0.0:8000 config.wsgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - speech_text_prod_network

  postgres:
    image: postgres:latest
    container_name: speech_text_postgresql_prod
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - speech_text_prod_postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - speech_text_prod_network

  node:
    build: ./docker/node
    container_name: speech_text_node_prod
    working_dir: /django_application
    restart: "no"
    ports:
      - "6006:6006"
    volumes:
      - ./assets:/django_application:cached
    command: "npm i && npm run build-dev"
    # command: tail -f /dev/null

volumes:
  speech_text_prod_postgres-db:

networks:
  speech_text_prod_network:
