# Generated by Django 5.0.2 on 2024-03-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='content_as_html',
            field=models.TextField(null=True),
        ),
    ]
